/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/bundle': RouteRecordInfo<'/bundle', '/bundle', Record<never, never>, Record<never, never>>,
    '/bundle_builder': RouteRecordInfo<'/bundle_builder', '/bundle_builder', Record<never, never>, Record<never, never>>,
    '/CreateEvent': RouteRecordInfo<'/CreateEvent', '/CreateEvent', Record<never, never>, Record<never, never>>,
    '/F_CarpoolCreate': RouteRecordInfo<'/F_CarpoolCreate', '/F_CarpoolCreate', Record<never, never>, Record<never, never>>,
    '/F_details': RouteRecordInfo<'/F_details', '/F_details', Record<never, never>, Record<never, never>>,
    '/K_mybookings': RouteRecordInfo<'/K_mybookings', '/K_mybookings', Record<never, never>, Record<never, never>>,
    '/managevenue': RouteRecordInfo<'/managevenue', '/managevenue', Record<never, never>, Record<never, never>>,
    '/N_Event_Browsing': RouteRecordInfo<'/N_Event_Browsing', '/N_Event_Browsing', Record<never, never>, Record<never, never>>,
    '/N_mainPage': RouteRecordInfo<'/N_mainPage', '/N_mainPage', Record<never, never>, Record<never, never>>,
    '/O_CreateAcc': RouteRecordInfo<'/O_CreateAcc', '/O_CreateAcc', Record<never, never>, Record<never, never>>,
    '/O_CreateVenue': RouteRecordInfo<'/O_CreateVenue', '/O_CreateVenue', Record<never, never>, Record<never, never>>,
    '/O_CurrentCarpools': RouteRecordInfo<'/O_CurrentCarpools', '/O_CurrentCarpools', Record<never, never>, Record<never, never>>,
    '/O_EventInfo': RouteRecordInfo<'/O_EventInfo', '/O_EventInfo', Record<never, never>, Record<never, never>>,
    '/O_Login': RouteRecordInfo<'/O_Login', '/O_Login', Record<never, never>, Record<never, never>>,
    '/O_venueinfo': RouteRecordInfo<'/O_venueinfo', '/O_venueinfo', Record<never, never>, Record<never, never>>,
    '/payments': RouteRecordInfo<'/payments', '/payments', Record<never, never>, Record<never, never>>,
    '/reservations': RouteRecordInfo<'/reservations', '/reservations', Record<never, never>, Record<never, never>>,
    '/reserved_venues': RouteRecordInfo<'/reserved_venues', '/reserved_venues', Record<never, never>, Record<never, never>>,
    '/SeatSelection': RouteRecordInfo<'/SeatSelection', '/SeatSelection', Record<never, never>, Record<never, never>>,
    '/Setting': RouteRecordInfo<'/Setting', '/Setting', Record<never, never>, Record<never, never>>,
    '/stastistics': RouteRecordInfo<'/stastistics', '/stastistics', Record<never, never>, Record<never, never>>,
    '/venuebrowsing': RouteRecordInfo<'/venuebrowsing', '/venuebrowsing', Record<never, never>, Record<never, never>>,
    '/venuerequest': RouteRecordInfo<'/venuerequest', '/venuerequest', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes: '/'
      views: never
    }
    'src/pages/bundle.vue': {
      routes: '/bundle'
      views: never
    }
    'src/pages/bundle_builder.vue': {
      routes: '/bundle_builder'
      views: never
    }
    'src/pages/CreateEvent.vue': {
      routes: '/CreateEvent'
      views: never
    }
    'src/pages/F_CarpoolCreate.vue': {
      routes: '/F_CarpoolCreate'
      views: never
    }
    'src/pages/F_details.vue': {
      routes: '/F_details'
      views: never
    }
    'src/pages/K_mybookings.vue': {
      routes: '/K_mybookings'
      views: never
    }
    'src/pages/managevenue.vue': {
      routes: '/managevenue'
      views: never
    }
    'src/pages/N_Event_Browsing.vue': {
      routes: '/N_Event_Browsing'
      views: never
    }
    'src/pages/N_mainPage.vue': {
      routes: '/N_mainPage'
      views: never
    }
    'src/pages/O_CreateAcc.vue': {
      routes: '/O_CreateAcc'
      views: never
    }
    'src/pages/O_CreateVenue.vue': {
      routes: '/O_CreateVenue'
      views: never
    }
    'src/pages/O_CurrentCarpools.vue': {
      routes: '/O_CurrentCarpools'
      views: never
    }
    'src/pages/O_EventInfo.vue': {
      routes: '/O_EventInfo'
      views: never
    }
    'src/pages/O_Login.vue': {
      routes: '/O_Login'
      views: never
    }
    'src/pages/O_venueinfo.vue': {
      routes: '/O_venueinfo'
      views: never
    }
    'src/pages/payments.vue': {
      routes: '/payments'
      views: never
    }
    'src/pages/reservations.vue': {
      routes: '/reservations'
      views: never
    }
    'src/pages/reserved_venues.vue': {
      routes: '/reserved_venues'
      views: never
    }
    'src/pages/SeatSelection.vue': {
      routes: '/SeatSelection'
      views: never
    }
    'src/pages/Setting.vue': {
      routes: '/Setting'
      views: never
    }
    'src/pages/stastistics.vue': {
      routes: '/stastistics'
      views: never
    }
    'src/pages/venuebrowsing.vue': {
      routes: '/venuebrowsing'
      views: never
    }
    'src/pages/venuerequest.vue': {
      routes: '/venuerequest'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
